### PR TITLE
:sparkles: (JS syntax enhancment) Some JS syntax enhancment

### PR DESCRIPTION
**Pull request by hhochart**
- Function declaration & call is no longer white and is now orange
- Class instantiation is now blue according to PHP screenshot.

image

#4 Related (still WIP)

### CODE REVIEW

**Comment by sr-scott** [comment]
Stumbled upon this theme today and really like it but also felt the JS syntax highlighting could use a bit of work, so was pleased to see someone taking up the challenge! 😄 
Really like the look of the screenshot here! 
My only suggestion would be that object literal keys should probably use a different colour. Just my two cents :) 
Really appreciate the work so far! Look forward to seeing this merged!

**Comment by hhochart** [comment]
Thanks ! I tried to stay as close as possible to the original PHP syntax for the object literal keys, so that's why i left them white for now.

**Comment by sr-scott** [comment]
@hhochart29 You looking to fork the theme then?

**Comment by hhochart** [comment]
I did a fork and tried today to put my version on the marketplace but didn't seem to work. will give another try !

**Comment by sr-scott** [comment]
@hhochart29 I'll look out for it as I'd definitely like to see a version of this theme go forward but with better JS syntax support.

**Comment by hhochart** [comment]
There you go @sr-scott 
https://marketplace.visualstudio.com/items?itemName=hhochart29.outrun
You can submit PR or issue if you have something you'd like to see :)

**Comment by sr-scott** [comment]
Whoop! I'll move further discussion to your repo then :)

**Comment by chaosharmonic** [comment]
@hhochart29 throwing this here as your repo doesn't appear to have issues enabled and upstream looks unmaintained -- any way you'd consider also publishing this to the Open VSX registry?

It would make this accessible to downstream projects like Theia and VSCodium, which can't access the VS Code Marketplace for licensing reasons. (In particular, various Arch Linux distros ship with Code-OSS builds by default.)

Here's a link to [some relevant documentation from the OVSX wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by hhochart** [comment]
Hi @chaosharmonic , i've opened issues on my own fork. I'll take a look about publishing to OVSX. I'm quite busy atm but i'll look at this whenever i have few minutes :) thanks

**Pull request closed without merging**
